### ISSUE TITLE
Tunnelblick Warning: An error occured fetching IP address information before connecting

### ISSUE THREAD

**Issue by ndobbs** [Tunnelblick/Tunnelblick#515]
**Describe the bug**

While connecting to a VPN from our corp network a warning is presented to the tunnelblick client user. 
The warning states: "A problem occurred while checking this computer's apparent public IP address.
See the Console log for details.

![image](https://user-images.githubusercontent.com/3474164/50920357-31908600-1413-11e9-8052-a6dc21704045.png)

*Console Log:*
```
2019-01-09 13:18:31 Tunnelblick[1231] currentIPInfo(Name): Response had invalid characters. response = WAN_IP_1,WAN_IP_2
2019-01-09 13:18:31 Tunnelblick[1231] An error occured fetching IP address information before connecting
2019-01-09 13:18:45 Tunnelblick[1231] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SUsers-user1-Svpn_name--user1--config-Dtblk-SContents-SResources'
```

**To Reproduce**
1. Connect to OpenVPN server from a site with more than 1 Active WAN Links
2. See public IP address warning
3. Click OK..
4. Continue using the VPN normally.

**Expected behavior**
A connection to the VPN without a Warning message that appears.

**Additional context**
I have redacted any personal information such as usernames or public IP addresses. 
OS: Mac OSX 10.14.2
Tunnelblick Version: 3.7.8 (build 5180)

**Comment by jkbullard** [comment]
@ndobbs - Thanks for your report.

If this happens consistently, your corporate network is apparently intercepting the request to https://tunnelblick.net/ipinfo and modifying the response in a way that it is not accepted by Tunnelblick.

**Comment by FieldMrFive** [comment]
Same issue here.
MacOSX 10.14.2 and Tunnelblick 3.7.8 (build 5180)

This warning begins to show only since recently.

Console log:

> 2019-01-10 11:00:33 Tunnelblick[2871] currentIPInfo(Name): Response had invalid characters. response = 221.223.xxx.xxx,637xx,205.233.xxx.xxx
> 2019-01-10 11:00:33 Tunnelblick[2871] An error occured fetching IP address information before connecting 

The x stands for a number.
I don't understand why it doesn't pass this check.
https://github.com/Tunnelblick/Tunnelblick/blob/cdd6ff424d0ea5f38efa365d94d78a4f09c75997/tunnelblick/VPNConnection.m#L1110

**Comment by jkbullard** [comment]
@FieldMrFive - Thanks for your very helpful info.

The problem is the trailing \r\n. It is a problem on the tunnelblick.net webserver. It only affects the fetch of IP address info, not the rest of the website.

It is being looked into.

**Comment by jkbullard** [comment]
This problems was caused by a problem on the Tunnelblick website that was fixed about 04:00 UTC on 2019-01-10.

**Comment by waboqin** [comment]
Hi @jkbullard ,
  This issue still there with the version 3.7.9a.

**Comment by jkbullard** [comment]
@waboqin - Thanks for your report.
 1. Does this happen every time you connect, or only sometimes?
 2. What does the [Console Log](https://tunnelblick.net/cConsoleLog.html) say?

**Comment by waboqin** [comment]
Hi @jkbullard,
 It happens to me every time when i connect( that means i haven't connected success once yet),some of my colleges also meet the same problem. Some colleges meet this issue only sometimes. by the way , we all use MAC.

Followings are part of the logs. Wish it can make some help:
Console Log:

2019-06-25 13:34:22.429746 Tunnelblick[6001] Cleared 'expect disconnect 0 -SLibrary-SApplication Support-STunnelblick-SUsers-Si347131-Swazh-Dtblk-SContents-SResources'
2019-06-25 13:35:06.306882 Tunnelblick[6001] currentIPInfo(Name): IP address info could not be fetched within 43.6 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x6000023bd9e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}'; the response was '(null)'
2019-06-25 13:35:06.307289 Tunnelblick[6001] An error occured fetching IP address information before connecting
2019-06-25 13:40:08.488017 Tunnelblick[6001] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SUsers-Si347131-Swazh-Dtblk-SContents-SResources'
2019-06-25 13:40:17.552997 Tunnelblick[6001] Cleared 'expect disconnect 0 -SLibrary-SApplication Support-STunnelblick-SUsers-Si347131-Swazh-Dtblk-SContents-SResources'
2019-06-25 13:40:52.169760 Tunnelblick[6001] currentIPInfo(Name): IP address info could not be fetched within 34.3 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x60000233c7b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}'; the response was '(null)'

**Comment by jkbullard** [comment]
@waboqin Thanks for the Console Log listings and other info.

In our experience, this problem happens randomly about 0.1% of the time -- that is, about 1 time per thousand attempts. This is presumably due to network congestion or other transitory problems.

This warning, if not accompanied by other warnings, does not mean that you haven't connected to the VPN properly. It just means that Tunnelblick was not able to test whether your IP address changed. It does that by accessing the Tunnelblick website before you connect, and then again after you connect; each time the Tunnelblick website returns your IP address, so Tunnelblick can warn you if the IP address didn't change. That isn't necessarily a problem because for some uses of a VPN you don't want the IP address to change.

The Tunnelblick program and Tunnelblick website are working and have been working fine. The only other thing that can cause this is a problem between your computer and the Tunnelblick website.

Our monitoring shows the website itself is OK. We monitor access to the Tunnelblick website from 15 networks distributed around the world, so the most likely explanation is a problem with your Internet connection.

Can you reach the [Tunnelblick website](https://tunnelblick.net/) in a browser?
Can you reach the ["IP checking" page](https://tunnelblick.net/ipinfo)? (The response should be en empty page that just shows something like 221.223.xxx.xxx,637xx,205.233.xxx.xxx (where each of the "x"s is a digit).

Can you connect your VPN (ignoring the warning) and then reach those two pages? If so, that would tend to support the idea that it is a problem with your Internet access.

**Comment by waboqin** [comment]
Hi @jkbullard  ,
I tried. connect the VPN. no matter i use proxy or not, i can't open the two pages.

**Comment by waboqin** [comment]
HI @jkbullard ,
By the way ,we're in China, as some of my colleges can use the VPN, so i guess there's nothing with the location right?

**Comment by jkbullard** [comment]
I think it **is** a location problem. I think the "Great Firewall" is blocking your access to tunnelblick.net. (Something is blocking it, anyway.) Perhaps your colleagues are using a different network to access it, or are using different DNS resolvers. 

If tunnelblick.net is blocked:
 1. You can't get to the Tunnelblick website using a browser; and
 2. The Tunnelblick program cannot check your IP address.

So I suggest that you remove the check from the "Check if apparent public IP address changed after connecting" box on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window. Be sure to select the configuration(s) you wish the change to apply to before removing the check.

You can test your IP address after connecting the VPN using any IP address checking website, for example, https://whatismyipaddress.com.

**Comment by waboqin** [comment]
Hi @jkbullard,
 I will try it. 
 Thanks for your help and quick response. 

B.R.

**Comment by abdulmoizeng** [comment]
Thanks @jkbullard

**Comment by oldthreefeng** [comment]
> remove the check from the "Check if apparent public IP address changed after connecting" box on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window

Thanks to @jkbullard  , this helps me a lot ~

**Comment by xgqfrms** [comment]
> I think it **is** a location problem. I think the "Great Firewall" is blocking your access to tunnelblick.net. (Something is blocking it, anyway.) Perhaps your colleagues are using a different network to access it, or are using different DNS resolvers.
> 
> If tunnelblick.net is blocked:
> 
> 1. You can't get to the Tunnelblick website using a browser; and
> 2. The Tunnelblick program cannot check your IP address.
> 
> So I suggest that you remove the check from the "Check if apparent public IP address changed after connecting" box on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window. Be sure to select the configuration(s) you wish the change to apply to before removing the check.
> 
> You can test your IP address after connecting the VPN using any IP address checking website, for example, https://whatismyipaddress.com.

@jkbullard Thanks for your time!

**Comment by jkbullard** [comment]
@Alamoalone - It looks like you're being blocked by the Great Firewall of China.

**Comment by Alamoalone** [comment]
> @Alamoalone - It looks like you're being blocked by the Great Firewall of China.

But I was able to use it a couple days ago

**Comment by jkbullard** [comment]
The GFoC "learns".

**Comment by Alamoalone** [comment]
> The GFoC "learns".

Okay, I see ,thank you for your time

**Comment by onwp** [comment]
For any future visitors: 

If you have set custom DNS like 1.1.1.1 or 8.8.8.8 etc. just remove them from your network settings, try connecting to VPN again. It fixed my issue.

**Comment by jkbullard** [comment]
> If you have set custom DNS like 1.1.1.1 or 8.8.8.8 etc. just remove them from your network settings, try connecting to VPN again. It fixed my issue.

I don't think that your issue was "an error occurred fetching IP address information **before** connecting". It may have been "an error occurred fetching IP address information **after** connecting", which has completely different causes.

There are many different causes for both errors, but very few of them would be fixed by removing DNS servers from your settings.

Although doing that might avoid some issues, it has side effects, notably when you are **not** connected to a VPN. You probably had manually entered 1.1.1.1 or 8.8.8.8 into your network settings; by removing them you are now using whatever DNS your Internet Service provider specifies. That's not usually a good idea: some ISPs are notorious for abusing DNS info, and one of the purposes of a VPN is usually to avoid exposing your traffic to your ISP.

If you have manually specified DNS servers in your network setup and that is interfering with your VPN connection [1], a better alternative to removing them is to put a check in the "Allow changes to manually-set network settings" checkbox on the "Connecting & Disconnecting" tab in Tunnelblick's "Advanced Settings" window. That will avoid any side effects when a VPN is not connected, and will fix some problems caused by usual VPN setups.

[1] An example of this situation is when you need to use a DNS server located on the VPN network to access resources on the VPN network. Another would be if your VPN doesn't allow DNS queries to exit the VPN network.
