### ISSUE TITLE
3.8.0beta02 (build 5340) Unresponsive / 100% CPU after waking from sleep with VPN connected

### ISSUE THREAD

**Issue by felixbuenemann** [Tunnelblick/Tunnelblick#550]
**Describe the bug**
After updating to Tunnelblick 3.8.0beta02 (build 5340) using the built-in updater this morning, 
I connected to work VPN from my home office.

The new version showed a warning, that my local routers IPv4 and IPv6 servers where still active, which I dismissed (the VPN only pushed specific routes and domains for split DNS, so this is ok).

Despite the warning the VPN and split-DNS was working fine.

Later I sent the system to sleep, disconnected it from the docking station, which also contains the ethernet connection and drove to work.

At work I woke the system from sleep. The VPN still showed as connected, the Tunnelblick.app was pegging the CPU at 100% / 100°C and the app was unresponsive. The menubar dropdown appeared after a very long, but was unresponsive. Keyboard input across all apps was broken.

After quitting (not force quitting) the app from activity monitor the system became responsive again and keyboard input was no longer clobbered.

The following lines were written to system log:

```
Jun  5 11:20:50 fixbook Tunnelblick[1683]: Cleared 'expect disconnect 0 -SLibrary-SApplication Support-STunnelblick-SUsers-Sfelix-SLOUIS INTERNET-Dtblk-SContents-SResources'
Jun  5 11:20:50 fixbook Tunnelblick[1683]: Preference 'LOUIS INTERNET-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
--- system in sleep mode from around 12:30 to 14:00 ---
Jun  5 14:02:23 fixbook Tunnelblick[1683]: Preference 'LOUIS INTERNET-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
Jun  5 14:11:15 fixbook Tunnelblick[1683]: SIGTERM (signal 15) received
Jun  5 14:11:21 fixbook Tunnelblick[1683]: Set 'expect disconnect 0 ALL'
Jun  5 14:11:22 fixbook Tunnelblick[1683]: Finished shutting down Tunnelblick; allowing termination
```

**To Reproduce**
1. Start Tunnelblick
2. Connect a VPN connection
3. Send system to standby mode
4. Wake system up in a different network
5. Observe high CPU usage and unresponsiveness of Tunnelblick.app

**Expected behavior**
Tunnelblick should have just disconnected either before or after waking from sleep.

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

Since the app was unresponsive, I couldn't follow the instructions, but I saved a sample of the program state from activity monitor:

[tunnelblick-hangs-after-wake-from-sleep-sample.txt](https://github.com/Tunnelblick/Tunnelblick/files/3257174/tunnelblick-hangs-after-wake-from-sleep-sample.txt)

**Comment by jkbullard** [comment]
Belated thanks for your report.

Please post the diagnostic info from a successful connect/disconnect (per the instructions in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) (ignoring the sleep/wake issue).

**Comment by jkbullard** [comment]
This _may_ be fixed in Tunnelblick 3.8.0beta03.

**Comment by felixbuenemann** [comment]
> Please post the diagnostic info from a successful connect/disconnect (per the instructions in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) (ignoring the sleep/wake issue).

When I reported the problem, I was connected through the Gigabit Ethernet in my CalDigit TB3 Plus Dock, which I have moved from my home office to my work office a few days ago, so I can't test in that exact setup right now.

Instead here's a diagnostic log when connecting from home via WiFi:

[tunnelblick-diag.txt](https://github.com/Tunnelblick/Tunnelblick/files/3340763/tunnelblick-diag.txt)

I'll try to reproduce the problem on 3.8.0beta03 next week.

**Comment by jkbullard** [comment]
@felixbuenemann - Thanks for the diagnostic info.

Your setup seems to be susceptible to a bug that was fixed in 3.8.0beta03. Please let me know if the hang doesn't happen with that version of Tunnelblick.

**Comment by felixbuenemann** [comment]
@jkbullard Just retried on 3.8.0beta04 and the bug still happens.

I also noticed that memory usage for Tunnelblick is fluctuating a lot, but growing overall. Currently it peaked at 6 GB physical memory and 3 GB privagte memory and then dropped back to 4 GB / 727 MB.

I also recorded a time profile trace in Instruments and it looks like Tunnelblick ist reading the VPN connection state and refreshing the UI like crazy.

[TimeProfilerTrace.zip](https://github.com/Tunnelblick/Tunnelblick/files/3372346/TimeProfilerTrace.zip)

**Comment by felixbuenemann** [comment]
@jkbullard I also looked at the OpenVPN log and it logs this over and over:

```
1562665728.234330 46000083 MANAGEMENT: CMD 'hold release'
1562665728.234343 40 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
1562665728.234351 40 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
1562665728.234391 28000003 MANAGEMENT: >STATE:1562665728,RESOLVE,,,,,,
1562665728.234876 4000021 RESOLVE: Cannot resolve host address: vpn.louis-net.de:1195 (nodename nor servname provided, or not known)
1562665728.234899 28000003 MANAGEMENT: >STATE:1562665728,RESOLVE,,,,,,
1562665728.235358 4000021 RESOLVE: Cannot resolve host address: vpn.louis-net.de:1195 (nodename nor servname provided, or not known)
1562665728.235370 40 Could not determine IPv4/IPv6 protocol
1562665728.235401 1 SIGUSR1[soft,init_instance] received, process restarting
1562665728.235411 28000003 MANAGEMENT: >STATE:1562665728,RECONNECTING,init_instance,,,,,
```

The DNS resolution fails because we have a Split-Brain DNS setup, where louis-net.de is using different nameservers/zones for internal (LAN) and external (Internet) users and vpn.louis-net.de does not exist in the local zone.

Here's the full copy of the log:

[config.ovpn.769_0_1_0_49456.54428.openvpn.log.gz](https://github.com/Tunnelblick/Tunnelblick/files/3372434/config.ovpn.769_0_1_0_49456.54428.openvpn.log.gz)

**Comment by felixbuenemann** [comment]
Oh and I just looked at the `config.ovpn` and it also has set `resolv-retry infinite` which is probably the reason why it keeps on trying to resolve the vpn host.

**Comment by jkbullard** [comment]
@felixbuenemann - Thanks for all your work on this. (I was writing a response asking you to investigate whether this sort of thing is happening when you wrote your last two posts.)

What's happening is that OpenVPN is trying to connect, failing, and trying to reconnect "like crazy" and Tunnelblick is working hard simply trying to log all that activity. Tunnelblick's 100% CPU use is a side effect of OpenVPN trying to resolve the OpenVPN server's address in a tight loop. I'll consider trying to put in some kind of throttling to detect that situation, but the root cause is that OpenVPN is looping trying to resolve something that can't be resolved.

You never posted the diagnostic info (for a good reason), but you should consider removing `persist-tun` if you use that option in the OpenVPN configuration file. Then OpenVPN will shut down the connection completely (which will restore the original DNS and routing so things resolve properly) when it tries to reconnect.

Two more things you could try:
 * Add `persist-remote-ip` so that OpenVPN remembers and uses the IP address of the OpenVPN server, and thus avoids having to look it up during the reconnection attempt.
 * Reference the OpenVPN server by IP address in the OpenVPN configuration file.

but either of those may fail due to routing issues.

**Comment by felixbuenemann** [comment]
I think using `persist-remote-ip` cannot be used in this case, since vpn.louis-net.de uses weighted load balancing and failover over multiple WAN IPs.

So if a WAN link goes down, the VPN wouldn't automaticall fail over to another IP.

I'll try removing `persist-tun` and see if that helps.

However, there must be something else going on.

I just retried connecting from inside our company LAN and I get the same name resolution error, but Tunnelblick stays fully responsive and doesn't show any significant CPU load:

[tunnelblick-diag2.txt](https://github.com/Tunnelblick/Tunnelblick/files/3372930/tunnelblick-diag2.txt)

If you take a look at the `tunnelblick-diag2.txt` log, you can see that openvpn tries to resolve the host name every 5 seconds, but if you analyze the unix timestamps from the log I uploaded when the bug was happening, the resolve retries happen on average every 6 milliseconds and Tunnelblick sends a SIGUSR1 signal to openvpn roughly every 12 milliseconds.

Here's a small Ruby script to analyze the average distance between events in openvpn.log:

```ruby
#!/usr/bin/env ruby
c = 0
puts ARGF
  .each_line
  .lazy
  .select{|l| /SIGUSR1/.match? l}
  .map(&:to_f)
  .each_cons(2)
  .map{|p| c+=1; p[1] - p[0]}
  .sum
  .fdiv c
```

For resolves I checked for `/RESOLVE:/` instead.

Maybe the time profiler trace I uploaded can be useful in finding out what's going wrong.

**Comment by felixbuenemann** [comment]
@jkbullard I tried connecting from home with `persist-tun` disabled, but it failed to connect with multiple tries. After re-enabling `persist-tun` the connection worked immediately, not sure why.

Today I left the VPN Details window open while connected, then sent the notebook to sleep and drove to work, but when connected the machine at work the bug did not happen and DNS retries happened normally every 5 seconds.

Despite the VPN Details window being open, the only config difference was `resolv-retry 60` instead of `resolv-retry infinite`.

I'll have to make another try tomorrow with the VPN Details window open and `resolv-retry infinite` to find out what makes the difference.

**Comment by jkbullard** [comment]
@felixbuenemann - Thanks for the updates. I think I may have an explanation. Sorry this is such a long post, but it's a complicated situation and I want to fully explain my understanding of what's happening.

I was puzzled by why Tunnelblick doesn't start a completely new connection when the computer wakes up from sleep – your tunnelblick-diag2.txt log shows you have it set to do that, and doing that should avoid this problem.

I think what's happening is that although Tunnelblick shuts down the VPN when the computer goes to sleep, it is unable to completely disconnect (it isn't able to restore the original, pre-VPN DNS setup). When the computer wakes up Tunnelblick starts a completely new connection but, because the DNS is still set up to use the VPN's DNS server, it can't resolve. The log from tunnelblick-diag2.txt supports that, since it shows a completely new connection at 14:24:00.303869 and the resolution failures start within one second – this is a log from starting a new connection, apparently when the computer woke up.

A test for this would be for you to:
 1. Set up Tunnelblick to **not** reconnect when it wakes up from sleep (uncheck the box for that on the "Connecting and Disconnecting" tab of the "Advanced" settings window, but leave a check in the box for "Disconnect when computer goes to sleep");
 2. Connect to the VPN.
 3. Put the computer to sleep. (Be sure the computer is completely asleep. That can take tens of seconds in some situations -- if you have a laptop that pulses the power on light when sleeping that's a good indication that it's sleeping.)
 4. Wake up the computer in the same location.

Although the wakeup may result in the VPN being reconnected (if the DNS setup hasn't changed), if there was a problem disconnecting the VPN when the computer went to sleep, it should show up in the log. Because Tunnelblick didn't reconnect when the compute woke up, the "old" log should be displayed – the log showing the original connection and then the disconnection caused by the computer going to sleep. That _should_ show any problem that causes DNS to not be fully restored. 

If the test doesn't show any problem with restoring the network settings, then something else may or not be happening. The test is not foolproof because the disconnection script only tells macOS to restore DNS – it doesn't verify that DNS was actually restored.

--------------------------------

Now, why is the above problem causing 100% CPU utilization?

You wrote:
>  if you analyze the unix timestamps from the log I uploaded when the bug was happening, the resolve retries happen on average every 6 milliseconds and Tunnelblick sends a SIGUSR1 signal to openvpn roughly every 12 milliseconds.

SIGUSR1 is Tunnelblick telling OpenVPN to restart the connection. As far as I know, OpenVPN doesn't send it to itself (although I suppose that's a possibility).

The main question is "Why is Tunnelblick sending the SIGUSR1" so often?

Tunnelblick sends SIGUSR1 when it detects a specific network change and has been instructed to "Restart connection" in that situation (on the "While Connected" tab of Tunnelblick's "Advanced" setup window).

I think what is happening is that
 1. You're home (for example) with a network setup A (DNS servers, domain, etc.).
 2. You connect the VPN.
 3. Your network settings change because of the VPN; let's call that network setup V.
 4. You sleep the computer. _As hypothesized above, the VPN is disconnected but DNS was not restored properly._ This leaves us with network setup X (which might be the same as V or some mix of A and V.)
 5. You wake up the computer with a different network connection, let's call it network setup C, however, it may actually be setup X or have some components that are from X.
 6. Tunnelblick starts a new VPN connection.
 7. OpenVPN tries to connect but fails because it can't resolve the OpenVPN server's domain.
 8. Tunnelblick detects a network change and sends OpenVPN a SIGUSR1 to restart the VPN.
 9. OpenVPN tries to restart the VPN but fails because the server's domain doesn't resolve.
 10. _Something_ (OpenVPN, presumably) triggers a network change notice to Tunnelblick even though the network setup has not changed.
 11. Tunnelblick detects the change and sends OpenVPN a SIGUSR1 to restart the VPN
 12. Go go step 9.

It's caused by several circumstances, all of which must be present:
 * You have Tunnelblick set up to restart the connection when it detects some particular network change or changes. (That's a Tunnelblick default.)
 * Your OpenVPN setup cannot successfully restart a connection (may only happen in some circumstances, such as a new location).
 * When OpenVPN tries to restart the connection, it triggers a "network setup changed" notification.

I think the _best_ thing would be for you to change your OpenVPN setup so it can successfully restart a connection even on a different network than the network the VPN was started with. It is possible there's a bug in Tunnelblick preventing that (for example, a bug causing the DNS information to not be restore properly when the computer goes to sleep as described above), but it is much more common for such problems to be caused by OpenVPN misconfigurations.

As an alternative, you could try changing the setting from "Restart connection" to "Ignore" on the "Advanced" setup window. I'm not sure that will work, though.

I will look into having Tunnelblick throttle the SIGUSR1 restarts, too, independent of the outcome of your situation.

**Comment by felixbuenemann** [comment]
One thing that could be interesting:

When I send the notebook to sleep, the system takes some seconds to enter sleep mode, but I usually close the lid and remove the USB-C or Thunderbolt connection to the ethernet adapter immediately.

So it is entirely possible that the network device that was used to establish the VPN connection goes away while the VPN is trying to shut down.

It is definitely gone when the notebook wakes from sleep at work.

I also noted at home that if I unplug the ethernet adapter while connected to VPN, Tunnelblick will not try to reconnect over Wifi, even though the connection is active.

It will try to reconnect automatically if I plug the ethernet adapter back in, but at least the last time I tried that did not work. I had to manually disconnect and reconnect to get the tunnel back up.

I should probably watch the logs and see what happens when I unplug and replug the ethernet adapter.

This situation is a bit special, since with an integrated ethernet port or wifi the connection might go down (disconnect wifi, unplug cable), but the network device itself is still present.

**Comment by jkbullard** [comment]
Yes, losing the primary network interface could interfere with restoration of network settings. I assume it loses the "network service" listed in System Preferences : Network.

Tunnelblick assumes that the down script runs in the same network environment as the up script. So the down script restores the network configuration to the same network service that the up script modified.

If that network service disappears (as opposed to becomes inactive but is still listed), that might cause the restore to have no effect.

You could test this with the test I described above, which, by not reconnecting on wakeup, preserves the down script log. See if, in the down script log, there is a complaint that it is "Ignoring change of Network Primary Service from <psid_when_up_script_was_run}>to <current_psid}>. I would expect that to appear if you remove the network adapter immediately, but not if you wait until the computer is really asleep before removing it.

I'll think about how (and if!) Tunnelblick could handle this situation better.

**Comment by jkbullard** [comment]
The following command will tell Tunnelblick to do extra logging in the up and down scripts, including info on network settings _after_ Tunnelblick has changed them:

    defaults write net.tunnelblick.tunnelblick DB-UP -bool yes

To remove the extra logging:

    defaults delete net.tunnelblick.tunnelblick DB-UP

**Comment by felixbuenemann** [comment]
Thanks for the extra debugging tricks.

I checked the cli and system preferences, the network devices continue to exist, even if the device is unplugged. They are just listed as inactive and `ifconfig` shows corresponding `en0` to `en7` devices with `status: inactive` and no ipv4 or ipv6 addresses.

**Comment by felixbuenemann** [comment]
I did some more testing today.

The problem is not disconnecting or shutting down the connection.

I can trigger the bug just by trying to connect at work as long as these facts are true:

* `resolv-retry infinite` is set
* remote endpoint cannot be resolved

If I set `resolv-retry 30` then the VPN Details title bar shows "Waiting for name resolution" and things are fine. If I set `resolv-retry infinite` then Tunnelblick shows "Trying to reconnect" in the VPN Details tilte bar and starts spamming the openvpn process  with SIGUSR1 signals and the UI becomes unresponsive.

If I kill only the Tunnelblick process (using force kill), leave `openvpn` running and then start Tunnelblick again it resumes spamming.

While Tunnelblick is killed I can look at the openvpn log and nothing strange is happening, it only logs that the managemnt client disconnected due to broken pipe (no surprise).

Other settings like persist-tun active or inactive do not influence the problem.

**Comment by jkbullard** [comment]
This problem may have been fixed in Tunnelblick 4.0.0beta05, released yesterday.
 - It limits the amount of the OpenVPN log that is displayed in the log in the "VPN Details" window. When OpenVPN adds too many entries to the log file too quickly, Tunnelblick displays a note instead of displaying all of the entries.
 - Separately, whenever the OpenVPN log file becomes too large, Tunnelblick truncates (clears) it – see #739.
