### ISSUE TITLE
OpenVpn not connecting and have issues

### ISSUE THREAD

**Issue by Nicwilco** [Tunnelblick/Tunnelblick#617]
**Describe the bug**
At first I had my a message that my VPN adress doesn't change so there was a problem, I go in the settings of the VPN and I "check" the "route all the trafic IPV4 in the VPN" (My Tunnelblick is in french so in french this is the check : Router tout le trafic IPV4 à travers le VPN)

Than no more message of the VPN but still nothing working I cannot even connect on the checking VPN adress of tunnelblick

**To Reproduce**
So I download tunnelblick I put a crt in my cerficicat (I am on MacOS) 
I use the .ovpn doc it goes on .tlbk then I put my name and password all is fine then I done what is write up

**Expected behavior**
to connect in the VPN that I need for go on filemakerpro and work on a little program with a friend

**Screenshots**

**Additional context**

**Diagnostic information**
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
macOS 10.15.2 (19C57); Tunnelblick 3.8.2 (build 5480); 

**Diagnostic information**

2020-04-11 09:48:30.819962 Initialization Sequence Completed
2020-04-11 09:48:30.820116 MANAGEMENT: >STATE:1586591310,CONNECTED,SUCCESS,192.168.XX.X,XX.XXX.XXX.XXX,XXX,192.168.X.X,XXX.XX
2020-04-11 09:48:31.143407 *Tunnelblick: DNS address 192.168.xx.xxx is being routed through the VPN
2020-04-11 09:48:35.343387 *Tunnelblick: process-network-changes: A system configuration change was ignored
2020-04-11 09:49:14.559620 *Tunnelblick: After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
2020-04-11 09:49:53.054664 *Tunnelblick: An error occured fetching IP address information using the ipInfo host's IP address after connecting

Thanks by advance for helping

**Comment by jkbullard** [comment]
@Nicwilco - Please post the complete diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by Nicwilco** [comment]
@jkbullard 
Here it is.
Thank's by the way for be there so quickly :)


*Tunnelblick: macOS 10.15.2 (19C57); Tunnelblick 3.8.3beta01 (build 5490); Admin user
git commit b44a1fd2c3b0393d1923d37c3a51bbf978cf8dbd


Configuration sodaco

"Sanitized" condensed configuration file for /Library/Application Support/Tunnelblick/Shared/sodaco.tblk:

client
dev tap
proto tcp
remote xx.xxx.xxx.xxx xxx
resolv-retry infinite
nobind
persist-key
persist-tun
ca   sodaco-ca.crt
ns-cert-type server
comp-lzo
verb 3
auth-user-pass


================================================================================

Files in sodaco.tblk:
      Contents/Resources/sod….crt
      Contents/Resources/config.ovpn

================================================================================

Configuration preferences:

-routeAllTrafficThroughVpn = 1
-keychainHasUsernameAndPassword = 1
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0
-alwaysShowLoginWindow = 1
-lastConnectionSucceeded = 1

================================================================================

Wildcard preferences:

-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0

================================================================================

Program preferences:

launchAtNextLogin = 1
tunnelblickVersionHistory = (
    "3.8.3beta01 (build 5490)",
    "3.8.2 (build 5480)"
)
lastLaunchTime = 608294290.918743
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = sodaco
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
NSWindow Frame ConnectingWindow = 470 433 500 322 0 0 1440 900 
NSWindow Frame ListingWindow = 593 99 500 422 0 0 1440 900 
detailsWindowFrameVersion = 5480
detailsWindowFrame = {{582, 342}, {920, 468}}
detailsWindowLeftFrame = {{0, 0}, {167, 350}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = log
leftNavSelectedDisplayName = sodaco
haveDealtWithOldTunTapPreferences = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUScheduledCheckInterval = 86400
SULastCheckTime = 2020-04-11 10:38:11 +0000
SUHasLaunchedBefore = 1
WebKitDefaultFontSize = 16
WebKitStandardFont = Times

================================================================================

Tunnelblick Log:

2020-04-11 13:01:42.467013 *Tunnelblick: macOS 10.15.2 (19C57); Tunnelblick 3.8.3beta01 (build 5490)
2020-04-11 13:01:42.809903 *Tunnelblick: Attempting connection with sodaco; Set nameserver = 769; monitoring connection
2020-04-11 13:01:42.810153 *Tunnelblick: openvpnstart start sodaco.tblk 49676 769 0 3 0 1098610 -ptADGNWradsgnw 2.4.8-openssl-1.1.1e
2020-04-11 13:01:42.835710 *Tunnelblick: openvpnstart starting OpenVPN
2020-04-11 13:02:02.629671 OpenVPN 2.4.8 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Mar 22 2020
2020-04-11 13:02:02.629869 library versions: OpenSSL 1.1.1e  17 Mar 2020, LZO 2.10
2020-04-11 13:02:02.632449 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:49676
2020-04-11 13:02:02.632491 Need hold release from management interface, waiting...
2020-04-11 13:02:02.915917 *Tunnelblick: openvpnstart log:
     Loading tap-notarized.kext
     OpenVPN started successfully.
     Command used to start OpenVPN (one argument per displayed line):
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.8-openssl-1.1.1e/openvpn
          --daemon
          --log /Library/Application Support/Tunnelblick/Logs/-SLibrary-SApplication Support-STunnelblick-SShared-Ssodaco.tblk-SContents-SResources-Sconfig.ovpn.769_0_3_0_1098610.49676.openvpn.log
          --cd /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources
          --machine-readable-output
          --setenv IV_GUI_VER "net.tunnelblick.tunnelblick 5490 3.8.3beta01 (build 5490)"
          --verb 3
          --config /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources/config.ovpn
          --setenv TUNNELBLICK_CONFIG_FOLDER /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources
          --verb 3
          --cd /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources
          --management 127.0.0.1 49676 /Library/Application Support/Tunnelblick/dckanalffhfnkmcbaoomipadokehggdikbcdabgj.mip
          --management-query-passwords
          --management-hold
          --redirect-gateway def1
          --script-security 2
          --route-up /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -a -d -f -m -w -ptADGNWradsgnw
          --down /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -a -d -f -m -w -ptADGNWradsgnw
          --route-pre-down /Applications/Tunnelblick.app/Contents/Resources/client.route-pre-down.tunnelblick.sh -9 -a -d -f -m -w -ptADGNWradsgnw
2020-04-11 13:02:02.919306 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:49676
2020-04-11 13:02:02.954549 *Tunnelblick: Established communication with OpenVPN
2020-04-11 13:02:02.956142 MANAGEMENT: CMD 'pid'
2020-04-11 13:02:02.956311 MANAGEMENT: CMD 'auth-retry interact'
2020-04-11 13:02:02.956386 MANAGEMENT: CMD 'state on'
2020-04-11 13:02:02.956473 MANAGEMENT: CMD 'state'
2020-04-11 13:02:02.956535 MANAGEMENT: CMD 'bytecount 1'
2020-04-11 13:02:03.059787 *Tunnelblick: >INFO:OpenVPN Management Interface Version 1 -- type 'help' for more info
2020-04-11 13:02:03.062571 MANAGEMENT: CMD 'hold release'
2020-04-11 13:02:07.471301 MANAGEMENT: CMD 'username "Auth" "jlc"'
2020-04-11 13:02:07.471462 MANAGEMENT: CMD 'password [...]'
2020-04-11 13:02:07.471641 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
2020-04-11 13:02:07.471669 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
2020-04-11 13:02:07.547437 TCP/UDP: Preserving recently used remote address: [AF_INET]85.234.213.196:443
2020-04-11 13:02:07.547552 Socket Buffers: R=[131072->131072] S=[131072->131072]
2020-04-11 13:02:07.547598 Attempting to establish TCP connection with [AF_INET]85.234.213.196:443 [nonblock]
2020-04-11 13:02:07.547617 MANAGEMENT: >STATE:1586602927,TCP_CONNECT,,,,,,
2020-04-11 13:02:19.066570 TCP connection established with [AF_INET]85.234.213.196:443
2020-04-11 13:02:19.066674 TCP_CLIENT link local: (not bound)
2020-04-11 13:02:19.066721 TCP_CLIENT link remote: [AF_INET]85.234.213.196:443
2020-04-11 13:02:19.066910 MANAGEMENT: >STATE:1586602939,WAIT,,,,,,
2020-04-11 13:02:20.372635 MANAGEMENT: >STATE:1586602940,AUTH,,,,,,
2020-04-11 13:02:20.372922 TLS: Initial packet from [AF_INET]85.234.213.196:443, sid=3a403c08 478e4974
2020-04-11 13:02:20.373381 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2020-04-11 13:02:21.350091 VERIFY OK: depth=1, C=BE, ST=brussels, L=brussels, O=sodaco, OU=rootca.sodaco.be, CN=sodaco CA, emailAddress=security@sodaco.be
2020-04-11 13:02:21.351276 VERIFY OK: nsCertType=SERVER
2020-04-11 13:02:21.351327 VERIFY OK: depth=0, C=BE, ST=brussels, O=sodaco, OU=rootca.sodaco.be, CN=rootca.sodaco.be
2020-04-11 13:02:22.646405 Control Channel: TLSv1, cipher SSLv3 DHE-RSA-AES256-SHA, 1024 bit RSA
2020-04-11 13:02:22.646516 [rootca.sodaco.be] Peer Connection Initiated with [AF_INET]85.234.213.196:443
2020-04-11 13:02:23.835107 MANAGEMENT: >STATE:1586602943,GET_CONFIG,,,,,,
2020-04-11 13:02:23.835408 SENT CONTROL [rootca.sodaco.be]: 'PUSH_REQUEST' (status=1)
2020-04-11 13:02:24.469751 PUSH: Received control message: 'PUSH_REPLY,route 192.168.15.0 255.255.255.0,route 192.168.17.0 255.255.255.0,route 85.234.202.16 255.255.255.248,route 192.168.18.0 255.255.255.0,route-gateway 192.168.10.1,ping 5,ping-restart 30,dhcp-option DNS 192.168.15.230,dhcp-option DOMAIN office.sodaco.be,ifconfig 192.168.10.2 255.255.255.0'
2020-04-11 13:02:24.469979 OPTIONS IMPORT: timers and/or timeouts modified
2020-04-11 13:02:24.470010 OPTIONS IMPORT: --ifconfig/up options modified
2020-04-11 13:02:24.470030 OPTIONS IMPORT: route options modified
2020-04-11 13:02:24.470048 OPTIONS IMPORT: route-related options modified
2020-04-11 13:02:24.470066 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2020-04-11 13:02:24.470446 Outgoing Data Channel: Cipher 'BF-CBC' initialized with 128 bit key
2020-04-11 13:02:24.470474 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
2020-04-11 13:02:24.470499 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
2020-04-11 13:02:24.470607 Incoming Data Channel: Cipher 'BF-CBC' initialized with 128 bit key
2020-04-11 13:02:24.470629 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
2020-04-11 13:02:24.470703 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
2020-04-11 13:02:24.470721 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.
2020-04-11 13:02:24.471810 TUN/TAP device /dev/tap0 opened
2020-04-11 13:02:24.471893 MANAGEMENT: >STATE:1586602944,ASSIGN_IP,,192.168.10.2,,,,
2020-04-11 13:02:24.472038 /sbin/ifconfig tap0 delete
                           ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
2020-04-11 13:02:24.487386 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2020-04-11 13:02:24.487508 /sbin/ifconfig tap0 192.168.10.2 netmask 255.255.255.0 mtu 1500 up
2020-04-11 13:02:24.490221 /sbin/route add -net 85.234.213.196 192.168.0.1 255.255.255.255
                           add net 85.234.213.196: gateway 192.168.0.1
2020-04-11 13:02:24.496456 /sbin/route add -net 0.0.0.0 192.168.10.1 128.0.0.0
                           add net 0.0.0.0: gateway 192.168.10.1
2020-04-11 13:02:24.499168 /sbin/route add -net 128.0.0.0 192.168.10.1 128.0.0.0
                           add net 128.0.0.0: gateway 192.168.10.1
2020-04-11 13:02:24.502133 MANAGEMENT: >STATE:1586602944,ADD_ROUTES,,,,,,
2020-04-11 13:02:24.502220 /sbin/route add -net 192.168.15.0 192.168.10.1 255.255.255.0
                           add net 192.168.15.0: gateway 192.168.10.1
2020-04-11 13:02:24.507851 /sbin/route add -net 192.168.17.0 192.168.10.1 255.255.255.0
                           add net 192.168.17.0: gateway 192.168.10.1
2020-04-11 13:02:24.510186 /sbin/route add -net 85.234.202.16 192.168.10.1 255.255.255.248
                           add net 85.234.202.16: gateway 192.168.10.1
2020-04-11 13:02:24.512440 /sbin/route add -net 192.168.18.0 192.168.10.1 255.255.255.0
                           add net 192.168.18.0: gateway 192.168.10.1
                           13:02:24 *Tunnelblick:  **********************************************
                           13:02:24 *Tunnelblick:  Start of output from client.up.tunnelblick.sh
                           13:02:26 *Tunnelblick:  Configuring tap DNS via OpenVPN
                           13:02:26 *Tunnelblick:  Retrieved from OpenVPN: name server(s) [ 192.168.15.230 ], domain name [ office.sodaco.be ], search domain(s) [ ], and SMB server(s) [ ]
                           13:02:26 *Tunnelblick:  Not aggregating ServerAddresses because running on macOS 10.6 or higher
                           13:02:26 *Tunnelblick:  Setting search domains to 'office.sodaco.be' because the search domains were not set manually (or are allowed to be changed) and 'Prepend domain name to search domains' was not selected
                           13:02:28 *Tunnelblick:  Saved the DNS and SMB configurations so they can be restored
                           13:02:28 *Tunnelblick:  Changed DNS ServerAddresses setting from '212.224.255.252 212.224.249.245' to '192.168.15.230'
                           13:02:28 *Tunnelblick:  Changed DNS SearchDomains setting from '' to 'office.sodaco.be'
                           13:02:28 *Tunnelblick:  Changed DNS DomainName setting from '' to 'office.sodaco.be'
                           13:02:28 *Tunnelblick:  Did not change SMB NetBIOSName setting of ''
                           13:02:28 *Tunnelblick:  Did not change SMB Workgroup setting of ''
                           13:02:28 *Tunnelblick:  Did not change SMB WINSAddresses setting of ''
                           13:02:28 *Tunnelblick:  DNS servers '192.168.15.230' will be used for DNS queries when the VPN is active
                           13:02:28 *Tunnelblick:  NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. Specify only known public DNS servers or DNS servers located on the VPN network to avoid such problems.
                           13:02:28 *Tunnelblick:  Flushed the DNS cache via dscacheutil
                           13:02:28 *Tunnelblick:  /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                           13:02:28 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
                           13:02:28 *Tunnelblick:  Not notifying mDNSResponderHelper that the DNS cache was flushed because it is not running
                           13:02:28 *Tunnelblick:  Setting up to monitor system configuration with process-network-changes
                           13:02:28 *Tunnelblick:  End of output from client.up.tunnelblick.sh
                           13:02:28 *Tunnelblick:  **********************************************
2020-04-11 13:02:28.325077 Initialization Sequence Completed
2020-04-11 13:02:28.325156 MANAGEMENT: >STATE:1586602948,CONNECTED,SUCCESS,192.168.10.2,85.234.213.196,443,192.168.0.3,52907
2020-04-11 13:02:28.541007 *Tunnelblick: DNS address 192.168.15.230 is being routed through the VPN
2020-04-11 13:02:32.733963 *Tunnelblick: process-network-changes: A system configuration change was ignored
2020-04-11 13:03:12.526340 *Tunnelblick: After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
2020-04-11 13:03:50.996664 *Tunnelblick: An error occured fetching IP address information using the ipInfo host's IP address after connecting
2020-04-11 13:04:06.690975 *Tunnelblick: process-network-changes: A system configuration change was ignored

================================================================================

Down log:

12:43:42 *Tunnelblick:  **********************************************
12:43:42 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
12:43:42 *Tunnelblick:  Cancelled monitoring system configuration changes
12:43:42 *Tunnelblick:  Restored State:DNS
12:43:42 *Tunnelblick:  Removed Setup:DNS
12:43:42 *Tunnelblick:  Removed State:SMB
12:43:42 *Tunnelblick:  Restored DNS and SMB settings
12:43:42 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
12:43:42 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
12:43:42 *Tunnelblick:  End of output from client.down.tunnelblick.sh
12:43:43 *Tunnelblick:  **********************************************

================================================================================

Previous down log:

09:53:07 *Tunnelblick:  **********************************************
09:53:07 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
09:53:07 *Tunnelblick:  Cancelled monitoring system configuration changes
09:53:07 *Tunnelblick:  Restored State:DNS
09:53:07 *Tunnelblick:  Removed Setup:DNS
09:53:08 *Tunnelblick:  Removed State:SMB
09:53:08 *Tunnelblick:  Restored DNS and SMB settings
09:53:08 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
09:53:08 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
09:53:08 *Tunnelblick:  End of output from client.down.tunnelblick.sh
09:53:08 *Tunnelblick:  **********************************************

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
iPhone
Wi-Fi
Bluetooth PAN
Thunderbolt Bridge

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	inet 127.94.0.1 netmask 0xff000000 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 24:1b:7a:cd:8a:0e 
	inet6 fe80::1cf7:8c42:87ed:fd33%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.0.3 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:18:5e:0d:16:c0 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:18:5e:0d:16:c0 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 06:1b:7a:cd:8a:0e 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 5e:96:3c:31:28:5f 
	inet6 fe80::5c96:3cff:fe31:285f%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 5e:96:3c:31:28:5f 
	inet6 fe80::5c96:3cff:fe31:285f%llw0 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::3475:ddcc:369f:2d25%utun0 prefixlen 64 scopeid 0xa 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::8bae:39d8:e4d5:e7a8%utun1 prefixlen 64 scopeid 0xb 
	nd6 options=201<PERFORMNUD,DAD>
tap0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 2e:40:7e:2c:e4:7a 
	inet 192.168.10.2 netmask 0xffffff00 broadcast 192.168.10.255
	media: autoselect
	status: active
	open (pid 6713)

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   96    0 0xffffff7f83bb7000 0x185000   0x185000   at.obdev.nke.LittleSnitch (5462) C4ED6BE7-4E64-3E8D-96FC-1128FF07626A <8 6 5 3 1>
  157    0 0xffffff7f83de2000 0x5000     0x5000     com.ScreamingBee.driver.SBVirtualMic64 (1.3.0) 770119B4-A271-33C3-8FAE-82CDE4B476DC <94 6 5 3>
  198    0 0xffffff7f83f48000 0x7000     0x7000     net.tunnelblick.tap (5300.3) 7CADB84E-01B1-3CD4-8FE3-CA4D2BE6C67E <8 6 5 1>

================================================================================

Quit Log:

2020-04-11 12:37:57.554011 applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes)
2020-04-11 12:37:57.618473 shutDownTunnelblick: started.
2020-04-11 12:37:57.619202 shutDownTunnelblick: Starting cleanup.
2020-04-11 12:37:57.620215 cleanup: Entering cleanup
2020-04-11 12:37:57.620945 cleanup aborted because Tunnelblick did not finish launching
2020-04-11 12:37:57.621916 shutDownTunnelblick: Cleanup finished.
2020-04-11 12:37:57.622633 Finished shutting down Tunnelblick; allowing termination

================================================================================

Console Log:

2020-04-11 08:49:29.059399 Tunnelblick[3495] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SUsers-Snicwilco-Ssodaco-Dtblk-SContents-SResources'
2020-04-11 08:51:35.013125 Tunnelblick[3495] cleanup: Entering cleanup
2020-04-11 08:51:35.013632 Tunnelblick[3495] synchronized user defaults
2020-04-11 08:51:35.463020 Tunnelblick[3495] Set 'expect disconnect 0 ALL'
2020-04-11 08:51:35.826598 Tunnelblick[3495] Finished shutting down Tunnelblick; allowing termination
2020-04-11 08:58:04.066043 Tunnelblick[4285] Tunnelblick: macOS 10.15.2; Tunnelblick 3.8.2 (build 5480)
2020-04-11 08:58:04.597797 Tunnelblick[4285] Tunnelblick cannot run when it is on /Volumes because the volume has the MNT_NOSUID statfs flag set.
2020-04-11 08:58:11.858037 Tunnelblick[4285] Tunnelblick doit :
                                         • Installé dans /Applications sous le nom Tunnelblick
                                         • Change le propriétaire et les permissions du logiciel pour le sécuriser
                                         • Sécurise les configurations
2020-04-11 08:58:11.858123 Tunnelblick[4285] Beginning installation or repair
2020-04-11 08:58:13.583143 Tunnelblick[4285] Installation or repair succeeded; Log:
                                       Tunnelblick installer started 2020-04-11 08:58:11.917079. 1 arguments: 0x0017
                                       getuid() = 501; getgid() = 20; geteuid() = 0; getegid() = 20
                                       Created directory /Library/Application Support/Tunnelblick with owner 0:80 and permissions 755
                                       Changed ownership of /Library/Application Support/Tunnelblick from 0:80 to 0:0
                                       Created directory /Library/Application Support/Tunnelblick/Logs with owner 0:0 and permissions 755
                                       Created directory /Library/Application Support/Tunnelblick/Shared with owner 0:0 and permissions 755
                                       Created directory /Library/Application Support/Tunnelblick/Tblks with owner 0:0 and permissions 755
                                       Created directory /Library/Application Support/Tunnelblick/expect-disconnect with owner 0:0 and permissions 755
                                       Created directory /Library/Application Support/Tunnelblick/Users with owner 0:0 and permissions 755
                                       Created directory /Library/Application Support/Tunnelblick/Users/nicwilco with owner 0:0 and permissions 755
                                       Created .mip
                                       Changed ownership of /Users/nicwilco/Library/Application Support/Tunnelblick from 501:20 to 501:80
                                       Changed ownership of /Users/nicwilco/Library/Application Support/Tunnelblick/Configurations from 501:20 to 501:80
                                       Copied /Volumes/Tunnelblick/Tunnelblick.app to /Applications/Tunnelblick.app
                                       Removed any 'com.apple.quarantine' extended attributes
                                       Changed ownership of /Applications/Tunnelblick.app and its contents from 501:80 to 0:0
                                       Need to replace and/or reload 'tunnelblickd':
                                           tunnelblickdHashOK   = NO
                                           launchctlPlistHashOK = NO
                                           tunnelblickdPlistOK  = YES
                                           socketOK             = YES
                                       Replaced /Library/LaunchDaemons/net.tunnelblick.tunnelblick.tunnelblickd.plist
                                       Used launchctl to load tunnelblickd
                                       Tunnelblick installer finished without error
2020-04-11 08:58:13.763203 Tunnelblick[4296] Tunnelblick: macOS 10.15.2; Tunnelblick 3.8.2 (build 5480)
2020-04-11 08:58:13.781773 Tunnelblick[4285] cleanup: Entering cleanup
2020-04-11 08:58:13.782516 Tunnelblick[4285] cleanup aborted because Tunnelblick did not finish launching
2020-04-11 08:58:13.784529 Tunnelblick[4285] Finished shutting down Tunnelblick; allowing termination
2020-04-11 08:58:26.745195 Tunnelblick[4296] Copied easy-rsa
2020-04-11 08:58:26.745423 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa
2020-04-11 08:58:26.745996 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-ca
2020-04-11 08:58:26.746305 Tunnelblick[4296] Changed permissions from 755 to 600 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/vars
2020-04-11 08:58:26.746755 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-key-server
2020-04-11 08:58:26.747031 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-key-pass
2020-04-11 08:58:26.747285 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-req
2020-04-11 08:58:26.747549 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-req-pass
2020-04-11 08:58:26.747801 Tunnelblick[4296] Changed permissions from 644 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/libressl.cnf.template
2020-04-11 08:58:26.748188 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3
2020-04-11 08:58:26.748411 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/ChangeLog
2020-04-11 08:58:26.748630 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/README
2020-04-11 08:58:26.749012 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3
2020-04-11 08:58:26.749373 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/x509-types
2020-04-11 08:58:26.749592 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/x509-types/ca
2020-04-11 08:58:26.749813 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/x509-types/server
2020-04-11 08:58:26.750016 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/x509-types/COMMON
2020-04-11 08:58:26.750227 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/x509-types/client
2020-04-11 08:58:26.750425 Tunnelblick[4296] Changed permissions from 644 to 600 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/openssl-1.0.cnf
2020-04-11 08:58:26.750687 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/easyrsa
2020-04-11 08:58:26.751014 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/easyrsa3/vars.example
2020-04-11 08:58:26.751409 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/COPYING
2020-04-11 08:58:26.751922 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc
2020-04-11 08:58:26.752189 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/Intro-To-PKI.md
2020-04-11 08:58:26.752441 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/EasyRSA-Readme.md
2020-04-11 08:58:26.752674 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/Hacking.md
2020-04-11 08:58:26.752883 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/EasyRSA-Advanced.md
2020-04-11 08:58:26.753280 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/TODO
2020-04-11 08:58:26.753525 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/doc/EasyRSA-Upgrade-Notes.md
2020-04-11 08:58:26.753880 Tunnelblick[4296] Changed permissions from 755 to 700 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/Licensing
2020-04-11 08:58:26.754195 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/Licensing/gpl-2.0.txt
2020-04-11 08:58:26.754516 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/KNOWN_ISSUES
2020-04-11 08:58:26.754914 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/EasyRSA-3/README.quickstart.md
2020-04-11 08:58:26.755227 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/clean-all
2020-04-11 08:58:26.755448 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-dh
2020-04-11 08:58:26.755657 Tunnelblick[4296] Changed permissions from 644 to 600 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/openssl-0.9.6.cnf
2020-04-11 08:58:26.755880 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/pkitool
2020-04-11 08:58:26.756094 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/sign-req
2020-04-11 08:58:26.756302 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-key-pkcs12
2020-04-11 08:58:26.756496 Tunnelblick[4296] Changed permissions from 644 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/whichopensslcnf
2020-04-11 08:58:26.756693 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-inter
2020-04-11 08:58:26.756904 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/README
2020-04-11 08:58:26.757192 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/revoke-full
2020-04-11 08:58:26.757460 Tunnelblick[4296] Changed permissions from 644 to 600 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/openssl-0.9.8.cnf
2020-04-11 08:58:26.757849 Tunnelblick[4296] Changed permissions from 644 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/readme-libressl.txt
2020-04-11 08:58:26.758174 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/TB-version.txt
2020-04-11 08:58:26.758575 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/list-crl
2020-04-11 08:58:26.758959 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/build-key
2020-04-11 08:58:26.759323 Tunnelblick[4296] Changed permissions from 755 to 500 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/inherit-inter
2020-04-11 08:58:26.759565 Tunnelblick[4296] Changed permissions from 644 to 600 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/openssl-1.0.0.cnf
2020-04-11 08:58:26.759817 Tunnelblick[4296] Changed permissions from 644 to 400 on /Users/nicwilco/Library/Application Support/Tunnelblick/easy-rsa/v3version.txt
2020-04-11 08:58:27.017726 Tunnelblick[4296] Sparkle: ===== Tunnelblick =====
2020-04-11 08:58:27.018414 Tunnelblick[4296] Sparkle: Verified appcast signature
2020-04-11 09:00:54.820599 Tunnelblick[4296] Converting/Installing /Applications/OpenVPN/sodaco.ovpn: One or more CR characters have been removed or replaced with LF characters
2020-04-11 09:00:54.826013 Tunnelblick[4296] Converting/Installing /Applications/OpenVPN/sodaco.ovpn: One or more CR characters have been removed or replaced with LF characters
2020-04-11 09:00:54.832615 Tunnelblick[4296] Converting/Installing /Applications/OpenVPN/sodaco.ovpn at line 26: Copied sodaco-ca.crt, removing CR characters
2020-04-11 09:00:54.833149 Tunnelblick[4296] Changed permissions from 644 to 740 on /private/var/folders/1n/hjtj5x2j6yjbmxl1xv7md96r0000gn/T/Tunnelblick-MMlhXA/sodaco.tblk/Contents/Resources/sodaco-ca.crt
2020-04-11 09:00:54.835506 Tunnelblick[4296] Converting/Installing /Applications/OpenVPN/sodaco.ovpn: Converted OpenVPN configuration
2020-04-11 09:01:03.568421 Tunnelblick[4296] Tunnelblick doit faire une action qui demande des privilèges d'administrateur.
2020-04-11 09:01:03.568565 Tunnelblick[4296] Beginning installation or repair
2020-04-11 09:01:03.684783 Tunnelblick[4296] Installation or repair succeeded; Log:
                                       Tunnelblick installer started 2020-04-11 09:01:03.650848. 3 arguments: 0x0001
                                            /Library/Application Support/Tunnelblick/Shared/sodaco.tblk
                                            /private/var/folders/1n/hjtj5x2j6yjbmxl1xv7md96r0000gn/T/Tunnelblick-MMlhXA/sodaco.tblk
                                       getuid() = 501; getgid() = 20; geteuid() = 0; getegid() = 20
                                       Copied /private/var/folders/1n/hjtj5x2j6yjbmxl1xv7md96r0000gn/T/Tunnelblick-MMlhXA/sodaco.tblk
                                           to /Library/Application Support/Tunnelblick/Shared/sodaco.tblk.temp
                                       Renamed /Library/Application Support/Tunnelblick/Shared/sodaco.tblk.temp
                                            to /Library/Application Support/Tunnelblick/Shared/sodaco.tblk
                                       Changed ownership of /Library/Application Support/Tunnelblick/Shared/sodaco.tblk and its contents from 501:20 to 0:0
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/sodaco.tblk
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources
                                       Changed permissions from 740 to 700 on /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources/sodaco-ca.crt
                                       Changed permissions from 740 to 700 on /Library/Application Support/Tunnelblick/Shared/sodaco.tblk/Contents/Resources/config.ovpn
                                       Tunnelblick installer finished without error
2020-04-11 09:03:41.186852 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:04:07.090110 Tunnelblick[4296] Can't find Keychain item to delete: service = 'Tunnelblick-Auth-sodaco'; account = 'username'; status was -25300: 'L’élément spécifié est introuvable dans le trousseau.'
2020-04-11 09:04:07.139813 Tunnelblick[4296] Can't find Keychain item to delete: service = 'Tunnelblick-Auth-sodaco'; account = 'password'; status was -25300: 'L’élément spécifié est introuvable dans le trousseau.'
2020-04-11 09:07:08.958807 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:15:10.307516 Tunnelblick[4296] Sparkle: Verified appcast signature
2020-04-11 09:21:54.763743 Tunnelblick[4296] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SShared-Ssodaco-Dtblk-SContents-SResources'
2020-04-11 09:21:54.777323 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:22:54.034915 Tunnelblick[4296] currentIPInfo(Name): IP address info could not be fetched within 38.6 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x600002430030 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 09:23:32.548116 Tunnelblick[4296] currentIPInfo(Address): IP address info could not be fetched within 38.5 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x60000240f150 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 09:23:32.548534 Tunnelblick[4296] An error occurred fetching IP address information after connecting
2020-04-11 09:24:52.825248 Tunnelblick[4296] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SShared-Ssodaco-Dtblk-SContents-SResources'
2020-04-11 09:24:52.851291 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:28:43.420558 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:29:38.287657 Tunnelblick[4296] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SShared-Ssodaco-Dtblk-SContents-SResources'
2020-04-11 09:29:39.203391 Tunnelblick[4296] currentIPInfo(Name): IP address info could not be fetched within 38.3 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x60000241c630 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 09:47:36.726662 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 09:49:14.559162 Tunnelblick[4296] currentIPInfo(Name): IP address info could not be fetched within 38.4 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x6000024250e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 09:49:53.053884 Tunnelblick[4296] currentIPInfo(Address): IP address info could not be fetched within 38.5 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x60000241d320 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 09:49:53.054166 Tunnelblick[4296] An error occurred fetching IP address information after connecting
2020-04-11 09:53:07.400757 Tunnelblick[4296] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SShared-Ssodaco-Dtblk-SContents-SResources'
2020-04-11 09:53:07.428606 Tunnelblick[4296] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 12:37:38.715866 Tunnelblick[6213] Tunnelblick: macOS 10.15.2; Tunnelblick 3.8.3beta01 (build 5490)
2020-04-11 12:37:39.284451 Tunnelblick[6213] Tunnelblick cannot run when it is on /Volumes because the volume has the MNT_NOSUID statfs flag set.
2020-04-11 12:37:54.516059 Tunnelblick[4296] SIGTERM (signal 15) received
2020-04-11 12:37:54.519894 Tunnelblick[4296] cleanup: Entering cleanup
2020-04-11 12:37:54.520603 Tunnelblick[4296] synchronized user defaults
2020-04-11 12:37:54.970171 Tunnelblick[4296] Set 'expect disconnect 0 ALL'
2020-04-11 12:37:55.334674 Tunnelblick[4296] Finished shutting down Tunnelblick; allowing termination
2020-04-11 12:37:55.643562 Tunnelblick[6213] Tunnelblick doit :
                                         • Installé dans /Applications sous le nom Tunnelblick
                                         • Change le propriétaire et les permissions du logiciel pour le sécuriser
                                         • Sécurise les configurations
2020-04-11 12:37:55.643651 Tunnelblick[6213] Beginning installation or repair
2020-04-11 12:37:57.378915 Tunnelblick[6213] Installation or repair succeeded; Log:
                                       Tunnelblick installer started 2020-04-11 12:37:55.703402. 1 arguments: 0x0017
                                       getuid() = 501; getgid() = 20; geteuid() = 0; getegid() = 20
                                       Moved /Applications/Tunnelblick.app to the Trash
                                       Copied /Volumes/Tunnelblick/Tunnelblick.app to /Applications/Tunnelblick.app
                                       Removed any 'com.apple.quarantine' extended attributes
                                       Changed ownership of /Applications/Tunnelblick.app and its contents from 501:80 to 0:0
                                       Need to replace and/or reload 'tunnelblickd':
                                           daemonHashesMatch  = NO
                                           plistHashesMatch   = YES
                                           activePlistMatches = YES
                                       Replaced /Library/LaunchDaemons/net.tunnelblick.tunnelblick.tunnelblickd.plist
                                       Used launchctl to load tunnelblickd
                                       Tunnelblick installer finished without error
2020-04-11 12:37:57.588016 Tunnelblick[6234] Tunnelblick: macOS 10.15.2; Tunnelblick 3.8.3beta01 (build 5490)
2020-04-11 12:37:57.620129 Tunnelblick[6213] cleanup: Entering cleanup
2020-04-11 12:37:57.620867 Tunnelblick[6213] cleanup aborted because Tunnelblick did not finish launching
2020-04-11 12:37:57.622547 Tunnelblick[6213] Finished shutting down Tunnelblick; allowing termination
2020-04-11 12:38:11.083351 Tunnelblick[6234] Sparkle: ===== Tunnelblick =====
2020-04-11 12:38:11.085061 Tunnelblick[6234] Sparkle: Verified appcast signature
2020-04-11 12:39:45.872360 Tunnelblick[6234] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 12:40:46.443853 Tunnelblick[6234] currentIPInfo(Name): IP address info could not be fetched within 39.0 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x600001ef3f30 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 12:40:51.250088 Tunnelblick[6234] Preference 'sodaco-skipWarningThatNotUsingSpecifiedOpenVPN' is TRUE, so not displaying the warning dialog.
2020-04-11 12:41:00.110795 Tunnelblick[6234] Removing *-skipWarningAboutDownroot
2020-04-11 12:41:00.110990 Tunnelblick[6234] Removing *-skipWarningAboutNoTunOrTap
2020-04-11 12:41:00.111116 Tunnelblick[6234] Removing *-skipWarningUnableToToEstablishOpenVPNLink
2020-04-11 12:41:00.111232 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptions
2020-04-11 12:41:00.111345 Tunnelblick[6234] Removing *-skipWarningThatNotUsingSpecifiedOpenVPN
2020-04-11 12:41:00.112025 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptionConflicts
2020-04-11 12:41:00.112179 Tunnelblick[6234] Removing *-skipWarningThatMayNotConnectInFutureBecauseOfOpenVPNOptions
2020-04-11 12:41:03.720952 Tunnelblick[6234] Removing *-skipWarningAboutDownroot
2020-04-11 12:41:03.721144 Tunnelblick[6234] Removing *-skipWarningAboutNoTunOrTap
2020-04-11 12:41:03.721274 Tunnelblick[6234] Removing *-skipWarningUnableToToEstablishOpenVPNLink
2020-04-11 12:41:03.721390 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptions
2020-04-11 12:41:03.721497 Tunnelblick[6234] Removing *-skipWarningThatNotUsingSpecifiedOpenVPN
2020-04-11 12:41:03.721602 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptionConflicts
2020-04-11 12:41:03.721719 Tunnelblick[6234] Removing *-skipWarningThatMayNotConnectInFutureBecauseOfOpenVPNOptions
2020-04-11 12:41:10.430591 Tunnelblick[6234] Removing *-skipWarningAboutDownroot
2020-04-11 12:41:10.430784 Tunnelblick[6234] Removing *-skipWarningAboutNoTunOrTap
2020-04-11 12:41:10.430910 Tunnelblick[6234] Removing *-skipWarningUnableToToEstablishOpenVPNLink
2020-04-11 12:41:10.431025 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptions
2020-04-11 12:41:10.431134 Tunnelblick[6234] Removing *-skipWarningThatNotUsingSpecifiedOpenVPN
2020-04-11 12:41:10.431241 Tunnelblick[6234] Removing *-skipWarningThatCannotConnectBecauseOfOpenVPNOptionConflicts
2020-04-11 12:41:10.431361 Tunnelblick[6234] Removing *-skipWarningThatMayNotConnectInFutureBecauseOfOpenVPNOptions
2020-04-11 12:41:25.034559 Tunnelblick[6234] currentIPInfo(Address): IP address info could not be fetched within 38.6 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x600001ec5860 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 12:41:25.034889 Tunnelblick[6234] An error occurred fetching IP address information after connecting
2020-04-11 13:01:47.912862 Tunnelblick[6234] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2020-04-11 13:01:52.913422 Tunnelblick[6234] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2020-04-11 13:01:57.914742 Tunnelblick[6234] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2020-04-11 13:03:12.525546 Tunnelblick[6234] currentIPInfo(Name): IP address info could not be fetched within 39.0 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x600001ed4990 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 13:03:50.993353 Tunnelblick[6234] currentIPInfo(Address): IP address info could not be fetched within 38.5 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "La requête a expiré." UserInfo={NSUnderlyingError=0x600001ed4f60 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "La requête a expiré." UserInfo={NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=La requête a expiré.}}, NSErrorFailingURLStringKey=https://205.233.73.116/ipinfo, NSErrorFailingURLKey=https://205.233.73.116/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=La requête a expiré.}'; the response was '(null)'
2020-04-11 13:03:50.993866 Tunnelblick[6234] An error occurred fetching IP address information after connecting

**Comment by jkbullard** [comment]
@Nicwilco - Did you close this because the problem has been solved?

Below is my response, written before I noticed you had closed this Issue:

<hr>

Taken together, these log entries:

> 2020-04-11 13:03:12.526340 *Tunnelblick: After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
> 2020-04-11 13:03:50.996664 *Tunnelblick: An error occured fetching IP address information using the ipInfo host's IP address after connecting

mean that after OpenVPN has set up the VPN, no https: traffic to IP address 205.233.73.116 [tunnelblick.net] was being returned.

That can have several causes, among them:
 * A firewall between your computer and the tunnelblick.net server blocking the connection, e.g. the Great Firewall of China, ISPs blocking OpenVPN traffic, etc.
 * A firewall on your computer blocking the connection, e.g. Little Snitch.
 * A problem with the routing set up by your OpenVPN server.
 * A problem with your OpenVPN server's access to/from tunnelblick.net

Perhaps Little Snitch is not configured to allow access?

**Comment by Nicwilco** [comment]
@jkbullard 
Sorry I make a mistake and kick on close and coment because my comment take a long time to go when i click just on comment.

So, no my issue is not solved, I read your response so i will look if i can do something on my firewall,
I am a newbie so if you can help me for the reste
I disinstal Little Snitch and it doesn't change anything, i was hoping it was that when you said it I say yeah maybe yes because i reinstall little snitch yesterday ^^
So no it's not that and I no that the server work because I have a friend on windows who is on it and all is fine. He try to help me but he use OpenVPN acces on Windows and he try to do the same with teamviewer on my computer and he coudn't then I say okay I seen on googe that tunnelblick is nice for do that and here we are^^ So thats what i can tell you :)
Thanks again for read me and response so quick !

**Comment by Nicwilco** [comment]
@jkbullard 
Hello,
I finnaly got it ! 
It was a problem with my proxy.
I had to select an option who says that my mac automatickly search & take new proxys.
So all is fine now :) 
Thank's for the help ! 
Have a nice day :)
