### ISSUE TITLE
MacOS FastUserSwitching makes Tunnelblick not responding/crashing

### ISSUE THREAD

**Issue by silv3r23** [Tunnelblick/Tunnelblick#738]
**To Reproduce**
Create 2 User Accounts A and B on your mac. Sign in to A, Sign in to B, while A is still active. Connect via Tunnelblick from B with this settings:
![grafik](https://user-images.githubusercontent.com/28316411/206685568-9aa07754-c9ed-4bc0-8878-f77283f4670d.png)

Once VPN connection is established, Switch to User A with FastUserSwitchting. Switch back to B.
Tunnelblick does not respond.

![grafik](https://user-images.githubusercontent.com/28316411/206685246-0e64b6ea-fd1b-409f-acbc-46303fbf87b1.png)

**Expected behavior**
Tunnelblick should not crash

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1

**Comment by victornpb** [comment]
I'm also experiencing the same issue

OS: macOS Ventura 13.2.1 (22D68) (intel)
Tunnelblick: macOS 13.2.1 (22D68); Tunnelblick 3.8.8a (build 5776); Admin user

I only have it Installed to a single user

**Comment by jkbullard** [comment]
This problem has been fixed in Tunnelblick 4.0.0beta05, released a few weeks ago.

 * It limits the amount of the OpenVPN log that is displayed in the log in the "VPN Details" window.
 * When OpenVPN adds too many entries to the log file too quickly, Tunnelblick displays a note instead of displaying all of the entries.
Separately, whenever the OpenVPN log file becomes too large, Tunnelblick truncates (clears) it – see https://github.com/Tunnelblick/Tunnelblick/issues/739.

**Comment by silv3r23** [comment]
I updated to Tunnelblick 4.0.0beta05 and still facing the same issue.

**Comment by jkbullard** [comment]
@silv3r23 - Thanks. I can't reproduce it on my test systems.

When this happens, please get a "Spin Dump" from the /Applications/Utilities/Activity Monitor. You can post it publicly, or send it to developers@tunnelblick.net.

**Comment by silv3r23** [comment]
> @silv3r23 - Thanks. I can't reproduce it on my test systems.
> 
> When this happens, please get a "Spin Dump" from the /Applications/Utilities/Activity Monitor. You can post it publicly, or send it to [developers@tunnelblick.net](mailto:developers@tunnelblick.net).

I have sent it to your email address right now.

**Comment by jkbullard** [comment]
@silv3r23 - Thanks. I've received it and will look into it.

**Comment by jkbullard** [comment]
@silv3r23 - Thanks again.

When this happens, before killing Tunnelblick please post the output from `ps -Alc | grep openvpn` executed in /Applications/Utilities/Terminal.

There shouldn't be anything sensitive in the output, but if you'd prefer to send it to developers@tunnelblick.net instead of posting it publicly, that's fine.

If there isn't any output, I'd like to know that.

**Comment by jkbullard** [comment]
@silv3r23 - Thanks. I think I understand what's happening. The fix may be complicated, but I'll work on it.

**Comment by jkbullard** [comment]
@silv3r23 - Please try Tunnelblick 4.0.0beta06. I think it fixes this problem.

**Comment by silv3r23** [comment]
@jkbullard yes it seems to be fixed, thanks a lot!!!
